image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - build
  - test

before_script:
  - apt-get update -qy
  - apt-get install -y nuget
  - cd src/VowelCount
  - dotnet restore
  - cd ../../tests/VowelCount.Tests
  - dotnet restore

build:
  stage: build
  script:
    - cd ../../src/VowelCount
    - dotnet build --configuration Release

test:
  stage: test
  script:
    - cd ../../tests/VowelCount.Tests
    - dotnet test --configuration Release
